---
title: "Module 1 Zusatzaufgabe"
format:
  html:
    embed-resources: true
editor: visual
---

## Stelle dich Git vor: Git configuration details

1.  Bearbeite den folgenden Code-Abschnitt und ersetze die Platzhalter durch deinen Namen und deine E-Mail-Adresse (anhand dieser Daten wird Git dich identifizieren, wenn du Änderungen vornimmst und diese gespeichert werden). **Beachte:** Die Anführungszeichen müssen beibehalten werden.

2.  Render das Dokument in dem du auf den "Render" Button klickst.

```{r}
library(usethis)
use_git_config(user.name = "Dein Name", user.email = "Deine Email")
```

## Übertrage deine Änderungen und speichere sie

1.  Navigiere zum Git-Bereich im Fenster oben rechts.

2.  Aktiviere das Kontrollkästchen neben der Datei git-configuration.qmd, um sie für den Commit vorzubereiten.

3.  Klicke auf die Schaltfläche “Commit”.

4.  Gib eine Commit-Nachricht in das Feld “Commit Message” ein (z.B. Git configuration abgeschlossen).

5.  Klicke auf die Schaltfläche “Commit”. Das Fenster, welches sich daraufhin öffnet kann geschlossen werden.

6.  Klicke auf die Schaltfläche “Push”.

7.  Gib deinen GitHub-Benutzernamen und deinen GitHub Personal Access Token (PAT) in die Felder "Username" und "Password" ein.

8.  Das Fenster kann geschlossen werden.

**Wichtig:** Du musst den GitHub Personal Access Token (PAT) eingeben, den du in der Vorbereitung auf den Kurs erstellt hast um deine Änderungen zurück an GitHub zu übertragen.

## Eröffne ein Issue auf GitHub

1.  Öffne [github.com](https://github.com/) in deinem Browser.

2.  Navigiere zur GitHub-Organisation für den Kurs: [github.com/rstatszh-k009](https://github.com/rstatszh-k009)

3.  Finde das Repository git-configuration-BENUTZERNAME, das mit deinem GitHub-Benutzernamen endet.

4.  Klicke auf die Schaltfläche "Issues".

5.  Klicke auf die grüne Schaltfläche "New issue".

6.  Schreibe in das Feld "Title": "Git configuration abgeschlossen".

7.  Markiere im Feld "Leave a comment" den Kursleiter mit @larnsce und hiterlasse eine Nachricht oder offene Frage.
